services:
  ipca-super-frontend:
    container_name: ipca-super-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - ipca-stack
    env_file:
      - .env

networks:
  ipca-stack:
    external: true
