services:
  ipca-frontend:
    container_name: ipca-super-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        VITE_IPCA_API: ${VITE_IPCA_API}
        VITE_IPCA_RT: ${VITE_IPCA_RT}
        VITE_IPCA_STUDENT_CODE_MINIO: ${VITE_IPCA_STUDENT_CODE_MINIO}
    restart: unless-stopped
    networks:
      - ipca-stack

networks:
  ipca-stack:
    external: true
