services:
  ipca-frontend:
    container_name: ipca-super-frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - ipca-stack
    args:
      VITE_IPCA_API: ${VITE_IPCA_API}
      VITE_IPCA_RT: ${VITE_IPCA_RT}
      VITE_IPCA_STUDENT_CODE_MINIO: ${VITE_IPCA_STUDENT_CODE_MINIO}

networks:
  ipca-stack:
    external: true
